# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  # before_all do
  #   # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  #   cocoapods
    
  # end

  # desc "Runs all the tests"
  # lane :test do
  #   scan
  # end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  # lane :beta do
  #   # match(type: "appstore") # more information: https://codesigning.guide
  #   gym # Build your app - more options available
  #   pilot

  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here (run `fastlane actions`)
  # end

  lane :update_credentials do
    sync_code_signing(
      type: "appstore",
      app_identifier: 'company.nicework.eventdotpizza',
      username: 'robot@nicework.company',
      team_id: '76YFR39J99',
      team_name: 'NiceWork OU',
      git_url: 'https://github.com/eralpkaraduman/event_dot_pizza_fastlane_match.git',
    )
  end

  lane :build do
    sync_code_signing(
      readonly: true,
      
      type: "appstore",
      app_identifier: 'company.nicework.eventdotpizza',
      username: 'robot@nicework.company',
      team_id: '76YFR39J99',
      team_name: 'NiceWork OU',
      git_url: 'https://github.com/eralpkaraduman/event_dot_pizza_fastlane_match.git',
      verbose: true
    )
    
    disable_automatic_code_signing(path: "Runner.xcodeproj")
    # build_app
  
    # upload_to_testflight

    # On iOS an extra build is required since flutter build builds an
    # .app rather than archiving .ipas for release.


    build_app(
      scheme: "Runner",
      export_options: {
        method: "app-store",
        provisioningProfiles: ENV['MATCH_PROVISIONING_PROFILE_MAPPING']
      }
    )
    enable_automatic_code_signing(path: "Runner.xcodeproj")
  end

  lane :upload do
    upload_to_testflight(
      # ipa: 'Runner.ipa',
      username: 'robot@nicework.company',
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      reject_build_waiting_for_review: true
    )
  end

  # desc "Deploy a new version to the App Store"
  # lane :release do
  #   # match(type: "appstore")
  #   # snapshot
  #   gym # Build your app - more options available
  #   deliver(force: true)
  #   # frameit
  # end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
