# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :android

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  lane :upload do
    upload_to_play_store(
      track: 'beta',
      apk_paths: [
        '../build/app/outputs/apk/release/app-armeabi-v7a-release.apk',
        '../build/app/outputs/apk/release/app-arm64-v8a-release.apk'
      ]
    )
    # slack(message: 'Successfully distributed a new beta build')
  end

  # You can define as many lanes as you want

  # after_all do |lane|
  #   # This block is called, only if the executed lane was successful

  #   # slack(
  #   #   message: "Successfully deployed new App Update."
  #   # )
  # end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
