name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Clone With Submodules
        uses: actions/checkout@v1
        with:
          submodules: true
          token: ${{ secrets.GITHUB_PAT }}

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: "Flutter: Install"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.10.15-pre.94"

      - name: "Flutter: Get Dependencies"
        run: flutter pub get

      - name: "Flutter: Tests"
        run: flutter test

      - name: "Flutter: Build Android"
        run: flutter build appbundle --release
#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.

