name: CI

on:
  push:
    branches:
      - integrate-fastlane

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Clone With Submodules
        uses: actions/checkout@v1
        with:
          submodules: true
          token: ${{ secrets.GITHUB_PAT }}

      - name: Install Fastlane
        run: bundle update

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: "Flutter: Install"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.9.1+hotfix.6"

      - name: "Flutter: Get Dependencies"
        run: flutter pub get

      #       - name: "Flutter: Running Tests"
      #         run: flutter test

      - name: "Flutter: Build Android"
        run: flutter build apk --release --split-per-abi

      - name: "Android: Upload Beta"
        run: (cd android && bundle exec fastlane beta)
      

# Set env variable
# FASTLANE_PASSWORD= robot@nicework.company apple id password
# MATCH_GIT_BASIC_AUTHORIZATION= ${{ secrets.GITHUB_PAT }}
# MATCH_PASSWORD = encryption password used by sigh

# Build ios

# build .app
# flutter build ios --release --no-codesign

# Run fastlane
# (cd ios && bundle exec fastlane)

#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.

